"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { RotateCcw, Send, Save } from "lucide-react";
import type { EmailTemplateKey, EmailTemplateContent } from "@/lib/resend";
import { saveEmailTemplate, resetEmailTemplate, sendEmailTemplateTest } from "../actions";

const T = {
  bg:      "var(--am1)",
  border:  "var(--aw09)",
  text:    "var(--atext2)",
  muted:   "var(--aw35)",
  purple:  "rgb(139,92,246)",
};

const inputStyle: React.CSSProperties = {
  width: "100%", background: "var(--am2)", border: `1px solid ${T.border}`,
  borderRadius: 10, padding: "10px 13px", color: T.text, fontSize: 13.5,
  outline: "none", boxSizing: "border-box", fontFamily: "inherit",
};

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div>
      <label style={{ color: T.muted, fontSize: 11.5, fontWeight: 700, display: "block", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.04em" }}>
        {label}
      </label>
      {children}
      {hint && <p style={{ color: T.muted, fontSize: 11.5, margin: "6px 0 0" }}>{hint}</p>}
    </div>
  );
}

export function EmailTemplateEditForm({
  templateKey, info, initialContent, defaultContent,
}: {
  templateKey: EmailTemplateKey;
  info: { label: string; description: string; tokens: string[]; hasCta: boolean };
  initialContent: EmailTemplateContent;
  defaultContent: EmailTemplateContent;
}) {
  const router = useRouter();
  const [subject, setSubject] = useState(initialContent.subject);
  const [heading, setHeading] = useState(initialContent.heading);
  const [body, setBody] = useState(initialContent.body);
  const [ctaLabel, setCtaLabel] = useState(initialContent.cta_label ?? "");
  const [saving, setSaving] = useState(false);
  const [resetting, setResetting] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [testTo, setTestTo] = useState("");
  const [sendingTest, setSendingTest] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);

  const doSave = async () => {
    setSaving(true);
    setError(null);
    setSaved(false);
    const res = await saveEmailTemplate(templateKey, { subject, heading, body, ctaLabel });
    setSaving(false);
    if (res.error) { setError(res.error); return; }
    setSaved(true);
    router.refresh();
  };

  const doReset = async () => {
    if (!confirm(`Reset "${info.label}" to its original copy? This discards your edits.`)) return;
    setResetting(true);
    setError(null);
    const res = await resetEmailTemplate(templateKey);
    setResetting(false);
    if (res.error) { setError(res.error); return; }
    setSubject(defaultContent.subject);
    setHeading(defaultContent.heading);
    setBody(defaultContent.body);
    setCtaLabel(defaultContent.cta_label ?? "");
    router.refresh();
  };

  const doSendTest = async () => {
    setSendingTest(true);
    setTestResult(null);
    // Test send uses whatever's currently saved, not the unsaved draft — save first if you've made changes.
    const res = await sendEmailTemplateTest(templateKey, testTo);
    setSendingTest(false);
    setTestResult(res.error ? `Failed: ${res.error}` : `Sent to ${testTo}`);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={{ background: T.bg, border: `1px solid ${T.border}`, borderRadius: 14, padding: 18, display: "flex", flexDirection: "column", gap: 14 }}>
        <Field label="Subject line">
          <input value={subject} onChange={e => setSubject(e.target.value)} style={inputStyle} />
        </Field>

        <Field label="Heading">
          <input value={heading} onChange={e => setHeading(e.target.value)} style={inputStyle} />
        </Field>

        <Field
          label="Body"
          hint={info.tokens.length > 0 ? `Available tokens: ${info.tokens.map(t => `{{${t}}}`).join(", ")}. Leave a blank line to start a new paragraph.` : "Leave a blank line to start a new paragraph."}
        >
          <textarea value={body} onChange={e => setBody(e.target.value)} rows={6} style={{ ...inputStyle, resize: "vertical" }} />
        </Field>

        {info.hasCta && (
          <Field label="CTA button text" hint="The button's destination link is generated by the app (e.g. the real reset/invite link) and can't be edited here.">
            <input value={ctaLabel} onChange={e => setCtaLabel(e.target.value)} style={inputStyle} placeholder={defaultContent.cta_label ?? ""} />
          </Field>
        )}

        {error && <p style={{ color: "rgb(248,113,113)", fontSize: 12.5, margin: 0 }}>{error}</p>}

        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <button
            disabled={saving}
            onClick={doSave}
            style={{ display: "flex", alignItems: "center", gap: 6, padding: "10px 18px", borderRadius: 10, border: "none", background: "rgb(124,58,237)", color: "white", fontSize: 13, fontWeight: 700, cursor: saving ? "default" : "pointer", opacity: saving ? 0.6 : 1 }}
          >
            <Save size={14} /> {saving ? "Saving…" : "Save changes"}
          </button>
          <button
            disabled={resetting}
            onClick={doReset}
            style={{ display: "flex", alignItems: "center", gap: 6, padding: "10px 16px", borderRadius: 10, border: `1px solid ${T.border}`, background: "transparent", color: T.muted, fontSize: 13, fontWeight: 600, cursor: resetting ? "default" : "pointer" }}
          >
            <RotateCcw size={13} /> Reset to default
          </button>
          {saved && <span style={{ color: "rgb(52,211,153)", fontSize: 12.5, fontWeight: 600 }}>Saved</span>}
        </div>
      </div>

      <div style={{ background: T.bg, border: `1px solid ${T.border}`, borderRadius: 14, padding: 18, display: "flex", flexDirection: "column", gap: 10 }}>
        <p style={{ color: T.text, fontSize: 13, fontWeight: 700, margin: 0 }}>Send a test email</p>
        <p style={{ color: T.muted, fontSize: 12, margin: 0 }}>Uses sample data (fake name, shop, dates) so you can see the real subject, copy, and CTA in an inbox. Sends the currently saved version — save first if you just made changes.</p>
        <div style={{ display: "flex", gap: 8 }}>
          <input value={testTo} onChange={e => setTestTo(e.target.value)} placeholder="you@example.com" style={{ ...inputStyle, flex: 1 }} />
          <button
            disabled={sendingTest || !testTo.trim()}
            onClick={doSendTest}
            style={{ display: "flex", alignItems: "center", gap: 6, padding: "10px 16px", borderRadius: 10, border: `1px solid ${T.border}`, background: "var(--am2)", color: T.text, fontSize: 13, fontWeight: 700, cursor: sendingTest || !testTo.trim() ? "default" : "pointer", opacity: sendingTest || !testTo.trim() ? 0.6 : 1, whiteSpace: "nowrap" }}
          >
            <Send size={13} /> {sendingTest ? "Sending…" : "Send test"}
          </button>
        </div>
        {testResult && <p style={{ color: testResult.startsWith("Failed") ? "rgb(248,113,113)" : "rgb(52,211,153)", fontSize: 12.5, margin: 0 }}>{testResult}</p>}
      </div>
    </div>
  );
}
